[package]
name = "blog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
rocket = "0.4.10"
rocket_contrib = { version = "0.4.10", features = ["json"] }
pulldown-cmark = "0.9.2"
